# Generated by Django 4.1.7 on 2023-07-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_image_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(max_length=30),
        ),
    ]
