# Generated by Django 4.1.7 on 2023-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_user_first_name_alter_user_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(upload_to="network/images"),
        ),
    ]
